// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Load environment variables (CommonJS-friendly)
const dotenv = require("dotenv");
dotenv.config();

const { defineConfig } = require("prisma/config");

module.exports = defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    provider: "postgresql",
    url: process.env["DATABASE_URL"] ?? "",
  },
});
